version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda

    steps:
      - checkout

      - run:
          name: Setup Python Env for tests
          command: |
            set -x
            conda-env create -f ./web/environment.yml

      - run:
          name: Run tests
          command: |
            set -e
            source activate BFEX
            pytest ./web

      - add_ssh_keys

      - run:
          name: Add Known Hosts
          command: |
            set -x
            ssh-keyscan ${DEPLOY_IP} > ~/.ssh/known_hosts

      # - run:
      #     name: Deploy
      #     command: |
      #       set -x
      #       rsync -avr -e ssh --exclude=".*/" . ${DEPLOY_USER}@${DEPLOY_IP}:~/BFEX
      #       ssh ${DEPLOY_USER}@${DEPLOY_IP} << EOF
      #         cd BFEX;
      #         sudo docker-compose down --remove-orphans
      #         sudo docker-compose build
      #         sudo docker-compose up -d
      #       EOF
